New file

diff --git a/cassandra/templates/default/debian.cassandra.init.erb b/cassandra/templates/default/debian.cassandra.init.erb
--- a/cassandra/templates/default/debian.cassandra.init.erb
+++ b/cassandra/templates/default/debian.cassandra.init.erb
@@ -1,5 +1,8 @@
 #! /bin/sh
-
+#
+# This file is managed by Chef.
+# Do NOT modify this file directly.
+#
 ### BEGIN INIT INFO
 # Provides:          cassandra
 # Required-Start:    $remote_fs $network $named $time
@@ -17,16 +20,20 @@ DESC="Cassandra"
 NAME=cassandra
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
-CASSANDRA_HOME=<%= node.cassandra.installation_dir %>
-CASSANDRA_CONF=<%= node.cassandra.conf_dir %>
+export CASSANDRA_HOME=<%= node.cassandra.installation_dir %>
+export CASSANDRA_CONF=<%= node.cassandra.conf_dir %>
 USER=<%= node.cassandra.user %>
-GROUP=<%= node.cassandra.user %>
+GROUP=<%= node.cassandra.group %>
 WAIT_FOR_START=10
-FD_LIMIT=100000
+FD_LIMIT=<%= node.cassandra.limits.nofile %>
+NODETOOL=$CASSANDRA_HOME/bin/nodetool
 
 [ -e $CASSANDRA_HOME/lib/apache-cassandra-<%= node.cassandra.version %>.jar ] || exit 0
 [ -e $CASSANDRA_CONF/cassandra.yaml ] || exit 0
 [ -e $CASSANDRA_CONF/cassandra-env.sh ] || exit 0
+[ -e $CASSANDRA_HOME/bin/cassandra ] || exit 0
+[ -e $NODETOOL ] || exit 0
+
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -63,13 +70,13 @@ do_start()
 
     start-stop-daemon --start \
         --quiet \
-        --oknodo \
+        --background \
         --chdir / \
         --oknodo \
         --chuid $USER:$GROUP \
         --exec /bin/bash \
         --pidfile $PIDFILE \
-        -- -c "$CASSANDRA_HOME/bin/cassandra -p $PIDFILE > /dev/null 2>&1"
+        -- -c "$CASSANDRA_HOME/bin/cassandra -p $PIDFILE > <%= node.cassandra.log_dir %>/boot.log 2>&1"
 
     is_running && return 0
 
@@ -89,6 +96,30 @@ do_start()
 do_stop()
 {
     is_running || return 1
+
+  # Disable Thrift, Mark node down for client
+  echo "executing nodetool disablethrift .."
+  $NODETOOL -h <%=node.ipaddress%> disablethrift
+  [ $? -eq 0 ] || {
+    echo "failed to execute disablethrift .."
+  }
+  sleep 2
+
+  # Disabling Gossip, Mark node down for cluster
+  echo "executing nodetool disablegossip .."
+  $NODETOOL -h <%=node.ipaddress%> disablegossip
+  [ $? -eq 0 ] || {
+    echo "failed to execute disablegossip .."
+  }
+  sleep 2
+
+  # Drain node for existing connections, Always safe even takes long time
+  echo "executing nodetool drain .."
+  $NODETOOL -h <%=node.ipaddress%> drain
+  [ $? -eq 0 ] || {
+    echo "failed to execute drain .."
+  }
+  sleep 2
 
     start-stop-daemon --stop \
         --pidfile $PIDFILE \
